### ISSUE TITLE
Avoid loading unused repository classes with `auto` repo type

### ISSUE THREAD

**Issue by dafyddcrosby** [facebook/between-meals#130]
The `rugged` extension is fine iff you're using git for your repository, otherwise it's additional weight when using the [`auto` repo](https://github.com/facebook/between-meals/blob/main/lib/between_meals/repo.rb#L37-L62). Since we're already `require`ing everything currently, we can consider `require`ing and testing the Ruby-language extensions first (ie hg and svn) and native extensions later (ie git). This does slightly change the behaviour such that if .hg or .svn are in your git repo, it will default to that repository type instead. However, in my *opinion* (note emphasis) once you're in a multi-repo setup like that you should be explicit on your repo type anyways and not rely on historical default behaviour.

**Comment by jaymzh** [comment]
I'm ok with that
