### ISSUE TITLE
Add option to detect symlinks in cookbookdirs as cookbooks

### ISSUE THREAD

**Issue by jaymzh** [facebook/between-meals#70]
It would be nice when handling multiple different environments to be able to treat these as changes so they can be detected and uploaded.

**Comment by jaymzh** [comment]
[ ] In `Changes::Cookbook.initialize` we should for each file store if it's a symlink
[ ] Add a config option for want_symlinks_to_count_as_cookbooks
[ ] Then in `Changes::Cookbook.meaningful_cookbook_file?` if the option is set and it's a symlink and it's in  a cookbook dir, return true.

**Comment by mikedodge04** [comment]
https://github.com/facebook/between-meals/pull/74

**Comment by davide125** [comment]
@jaymzh @mikedodge04 is there anything left to do here?

**Comment by jaymzh** [comment]
Closed by #74
