### ISSUE TITLE
between-meals can't install when rugged version is >= 0.27.0

### ISSUE THREAD

**Issue by bwann** [facebook/between-meals#90]
This is technically a rugged issue, but when installing between-meals on a fresh CentOS 7.5 + Chef 13.10.4 machine (adding to Chef's embedded gems) it apparently downloads the latest version of rugged from rubygems.org, which breaks things if it installs a version of rugged >= 0.27.0.

Rugged isn't able to create the Makefile, due to "Could NOT find OpenSSL":
https://gist.github.com/bwann/cbe5775471cc554a788e23fa7053f461

Manually installing rugged up to 0.26.0 first before between-meals works. I'm not sure what the real problem is here, looks like rugged changed something about how it was handling TLS and cmake in 0.27.0.

I'm not sure what the correct fix here is either, if between-meals needs to pin the rugged version, if this is something in the embedded Chef gem environment that needs fixed, or what.

Putting this here to track the issue in case other people hit it.

edit: same behavior on chef-14.4.56-1.el7.x86_64 too

**Comment by jaymzh** [comment]
We're moving to putting our tools ontop of chefdk, which is more friendly to these sorts of intrusions, and also means we can move our fleet to new versions of chef independently of tt/bm/gd/etc.... 

And that has 0.27:

$ /opt/chefdk/embedded/bin/gem list | grep rugged
rugged (0.27.1)


and seems to work. Give that a shot?

Also CC @NaomiReeves

**Comment by bwann** [comment]
Moving this and other stuff to chefdk LGTM
